# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            .svf
tagline:          'A Personal Website''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Scott Vranesh-Fallin'
  url:            https://twitter.com/allhandsmad

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/svf/svf.github.io
